@url = http://localhost:8800/api
POST http://localhost:8800/api/auth/register
Content-Type: application/json

{
  "username" : "user1",
  "email" : "user1@gmail.com",
  "password" : "user1",
  "country" : "USA"
}

###
POST {{url}}/auth/login
Content-Type: application/json

{
  "username" : "user1",
  "password" : "user1"
}

