
@url = http://localhost:8800/api
DELETE {{url}}/users/642af1385686b19ba3c87fba
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MmFmMTM4NTY4NmIxOWJhM2M4N2ZiYSIsImlzU2VsbGVyIjpmYWxzZSwiaWF0IjoxNjgwNTM2MTg0fQ.01Yqy4DZKkdZhfrNe5imF1hiCDJP9zhv4EtUIFugzYM